version: "3.2"
services:
  db:
    build:
      context: ./docker/db
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: les-bonnes-recettes-d-evy
      POSTGRES_PASSWORD: les-bonnes-recettes-d-evy
      POSTGRES_USER: evy
    ports:
      - 35432:5432
    